### ISSUE TITLE
Failed opening required '/var/www/html/roundcube_plugins/authres_status-0.6.1/../../vendor/autoload.php'

### ISSUE THREAD

**Issue by ThomasCr** [pimlie/authres_status#52]
The plugin is not able to include autoload.php

I know, I have a special setup. My plugin folder is symlinked to a folder outside of my roundcube folder.
But even, when I fix the path, it dont work:

I chance this:
```
                           $autoload = require slashify($this->home) . "../../vendor/autoload.php";
                            //$autoload = require __DIR__ . "/../../vendor/autoload.php";
```

So the path is like it was before - but I get the same error:

`Dec  9 10:28:03 srv1 roundcube: PHP Fatal error:  require(): Failed opening required '/var/www/html/webmail/plugins/authres_status/../../vendor/autoload.php' (include_path='/var/www/html/webmail/plugins/enigma/lib:/var/www/html/roundcubemail-1.5.1/vendor/pear/pear_exception:/var/www/html/roundcubemail-1.5.1/vendor/pear/console_getopt:/var/www/html/roundcubemail-1.5.1/vendor/pear/pear-core-minimal/src:/var/www/html/roundcubemail-1.5.1/vendor/pear/auth_sasl:/var/www/html/roundcubemail-1.5.1/vendor/pear/net_ldap2:/var/www/html/roundcubemail-1.5.1/vendor/pear/console_commandline:/var/www/html/roundcubemail-1.5.1/vendor/pear/mail_mime:/var/www/html/roundcubemail-1.5.1/vendor/pear/net_socket:/var/www/html/roundcubemail-1.5.1/vendor/pear/net_smtp:/var/www/html/roundcubemail-1.5.1/vendor/pear/crypt_gpg:/var/www/html/webmail/program/lib:.:/usr/share/php:/var/www/html/roundcubemail-1.5.1/program/lib') in /var/www/html/roundcube_plugins/authres_status-0.6.1/authres_status.php on line 430`

But the file is there:
```
root@srv1:~# ls -lah /var/www/html/webmail/vendor/autoload.php
-rw-r--r-- 1 www-data www-data 178 Nov 22 22:12 /var/www/html/webmail/vendor/autoload.php
```

I use PHP 7.4 with Roundcube 1.5.1

**Comment by ThomasCr** [comment]
ok, I updated authres_status.php to 

```
                            $autoload = require INSTALL_PATH."/vendor/autoload.php";
                            //$autoload = require __DIR__ . "/../../vendor/autoload.php";

```
but now I get:

```
Dec  9 10:50:23 srv1 roundcube: PHP Fatal error:  Uncaught Error: Class 'DKIM_Verify' not found in /var/www/html/roundcube_plugins/authres_status-0.6.1/authres_status.php:436
Dec  9 10:50:23 srv1 roundcube: Stack trace:
Dec  9 10:50:23 srv1 roundcube: #0 /var/www/html/roundcube_plugins/authres_status-0.6.1/authres_status.php(215): authres_status->get_authentication_status()
Dec  9 10:50:23 srv1 roundcube: #1 /var/www/html/roundcubemail-1.5.1/program/lib/Roundcube/rcube_plugin_api.php(513): authres_status->messages_list()
Dec  9 10:50:23 srv1 roundcube: #2 /var/www/html/roundcubemail-1.5.1/program/actions/mail/index.php(466): rcube_plugin_api->exec_hook()
Dec  9 10:50:23 srv1 roundcube: #3 /var/www/html/roundcubemail-1.5.1/program/actions/mail/list.php(123): rcmail_action_mail_index::js_message_list()
Dec  9 10:50:23 srv1 roundcube: #4 /var/www/html/roundcubemail-1.5.1/program/include/rcmail.php(275): rcmail_action_mail_list->run()
Dec  9 10:50:23 srv1 roundcube: #5 /var/www/html/roundcubemail-1.5.1/index.php(283): rcmail->action_handler()
Dec  9 10:50:23 srv1 roundcube: #6 {main}
Dec  9 10:50:23 srv1 roundcube:   thrown in /var/www/html/roundcube_plugins/authres_status-0.6.1/authres_status.php on line 436
```

which is already reported at https://github.com/pimlie/authres_status/issues/49

**Comment by pimlie** [comment]
Cleaning up issues, please reopen if this is still an issue
