### ISSUE TITLE
Fatal error on Ubuntu 22.04

### ISSUE THREAD

**Issue by Halfwalker** [pimlie/authres_status#55]
I just did a test install on Ubuntu 22.04/jammy, and get a Fatal error
```
[14-Jul-2022 12:00:07 America/New_York] PHP Fatal error:  Uncaught Error: Call to a member function loadClass() on int in /usr/share/roundcube/plugins/authres_status/authres_status.php:432
Stack trace:
#0 /usr/share/roundcube/plugins/authres_status/authres_status.php(216): authres_status->get_authentication_status()
#1 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(441): authres_status->messages_list()
#2 /usr/share/roundcube/program/steps/mail/func.inc(444): rcube_plugin_api->exec_hook()
#3 /usr/share/roundcube/program/steps/mail/list.inc(109): rcmail_js_message_list()
#4 /usr/share/roundcube/index.php(302): include_once('/usr/share/roun...')
#5 {main}
  thrown in /usr/share/roundcube/plugins/authres_status/authres_status.php on line 432
```

The system is built with the following setup :

Roundcube 1.4.3 from Ubuntu repos
```
$ dpkg -l round\* | fgrep ii
ii  roundcube               1.4.3+dfsg.1-1 all          skinnable AJAX based webmail solution for IMAP servers - metapackage
ii  roundcube-core          1.4.3+dfsg.1-1 all          skinnable AJAX based webmail solution for IMAP servers
ii  roundcube-mysql         1.4.3+dfsg.1-1 all          metapackage providing MySQL dependencies for RoundCube
ii  roundcube-plugins       1.4.3+dfsg.1-1 all          skinnable AJAX based webmail solution for IMAP servers - plugins
```
Nginx 1.18 from Ubuntu repos
```
$ dpkg -l nginx\* | fgrep ii
ii  nginx          1.18.0-0ubuntu1.3 all          small, powerful, scalable web/proxy server
ii  nginx-common   1.18.0-0ubuntu1.3 all          small, powerful, scalable web/proxy server - common files
ii  nginx-core     1.18.0-0ubuntu1.3 amd64        nginx web/proxy server (standard version)
```
PHP 7.4 from Ubuntu repos
```
$ dpkg -l php\* | fgrep ii
ii  php-auth-sasl            1.0.6-3                                    all          Abstraction of various SASL mechanism responses
ii  php-common               2:75                                       all          Common files for PHP packages
ii  php-imagick              3.4.4-4                                    amd64        Provides a wrapper to the ImageMagick library
ii  php-mail-mime            1.10.6-1                                   all          PHP PEAR module for creating MIME messages
ii  php-masterminds-html5    2.7.0+dfsg-3                               all          An HTML5 parser and serializer
ii  php-net-idna2            0.1.1-1                                    all          PHP Pear module for handling international domain names
ii  php-net-sieve            1.4.1-1                                    all          Handles talking to a sieve server
ii  php-net-smtp             1.9.0-1                                    all          PHP PEAR module implementing SMTP protocol
ii  php-net-socket           1.0.14-2                                   all          Network Socket Interface
ii  php-pear                 1:1.10.9+submodules+notgz-1ubuntu0.20.04.3 all          PEAR Base System
ii  php7.4                   7.4.3-4ubuntu2.12                          all          server-side, HTML-embedded scripting language (metapackage)
ii  php7.4-bz2               7.4.3-4ubuntu2.12                          amd64        bzip2 module for PHP
ii  php7.4-cli               7.4.3-4ubuntu2.12                          amd64        command-line interpreter for the PHP scripting language
ii  php7.4-common            7.4.3-4ubuntu2.12                          amd64        documentation, examples and common module for PHP
ii  php7.4-curl              7.4.3-4ubuntu2.12                          amd64        CURL module for PHP
ii  php7.4-dev               7.4.3-4ubuntu2.12                          amd64        Files for PHP7.4 module development
ii  php7.4-fpm               7.4.3-4ubuntu2.12                          amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php7.4-gd                7.4.3-4ubuntu2.12                          amd64        GD module for PHP
ii  php7.4-intl              7.4.3-4ubuntu2.12                          amd64        Internationalisation module for PHP
ii  php7.4-json              7.4.3-4ubuntu2.12                          amd64        JSON module for PHP
ii  php7.4-mbstring          7.4.3-4ubuntu2.12                          amd64        MBSTRING module for PHP
ii  php7.4-mysql             7.4.3-4ubuntu2.12                          amd64        MySQL module for PHP
ii  php7.4-opcache           7.4.3-4ubuntu2.12                          amd64        Zend OpCache module for PHP
ii  php7.4-pspell            7.4.3-4ubuntu2.12                          amd64        pspell module for PHP
ii  php7.4-readline          7.4.3-4ubuntu2.12                          amd64        readline module for PHP
ii  php7.4-xml               7.4.3-4ubuntu2.12                          amd64        DOM, SimpleXML, XML, and XSL module for PHP
ii  php7.4-zip               7.4.3-4ubuntu2.12                          amd64        Zip module for PHP
```

**Comment by pimlie** [comment]
Cleaning up old issues. Please reopen if a similar issue still occurs with php v8
